#!/usr/bin/env sh

#first configure disk partitioning, then run this script

if [[ $# != 2 ]]; then
    echo not enough args
    exit
fi

efipart=$1
rootpart=$2

read -p "Initialize EFI filesystem? [Y/n]" yn
case $yn in
    [Nn]* ) ;;
    * ) mkfs.fat -F 32 $efipart;;
esac

mkfs.ext4 $rootpart

mount $rootpart /mnt
mount --mkdir $efipart /mnt/boot

#update keys for live installer
pacman --noconfirm -Sy archlinux-keyring

#first installation, most important packages and install others later
pacstrap -K /mnt base base-devel linux linux-firmware linux-headers networkmanager git neovim polkit

#generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

cp ./stage2 /mnt/stage2

arch-chroot /mnt/ sh ./stage2
