#!/usr/bin/env sh

#set the time zone
ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
hwclock --systohc

#generate locales
echo en_US.UTF-8 UTF-8 > /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

#sudo tweaks
echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/00-wheel-can-sudo
echo "Defaults editor=/usr/bin/nvim" > /etc/sudoers.d/01-visudo-editor

#Make hostname
read -p 'Enter hostname: ' hostnm 
echo $hostnm > /etc/hostname

#enable networkmanager
systemctl enable NetworkManager

#install more packages
#can't install yay as root, need to do after new user is made
#git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
#yay -S $(cat packages.txt)

#prompt for root password
echo "pick your root password"
passwd 

#setup user account
read -p 'Enter username: ' user
useradd -mG wheel,uucp,network $user
echo "Enter password for account $user"
passwd $user

#Install i3?
read -p "Install i3? [Y/n]" yn
case $yn in
    [Nn]* ) ;;
    * ) pacman --noconfirm -S i3-gaps i3blocks feh xorg-server xorg-xinit ttf-liberation dmenu alacritty network-manager-applet xclip scrot xorg-xinput;
        git clone https://www.github.com/ryanKopp/dotfiles.git /home/$user/dotfiles
        sh /home/$user/deployConfigs
        ;;
esac

#Are we dual booting? 
read -p "Is this a dual boot installation? [y/N]" yn
case $yn in
    [Yy]* ) pacman --noconfirm -S os-prober;
        echo GRUB_DISABLE_OS_PROBER=false >> /etc/default/grub;
        os-prober
        ;;
    * ) ;;
esac

read -p "Is this a laptop? [y/N]" yn
case $yn in
    [Yy]* ) pacman --noconfirm -S tlp brightnessctl intel-ucode;
        ;;
    * ) ;;
esac

#get grub downloaded
pacman --noconfirm -S grub efibootmgr

#Install grub
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
