#!/usr/bin/env sh


ln -sf ~/dotfiles/bash_profile ~/.bash_profile
ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/xinitrc ~/.xinitrc

ln -sf ~/dotfiles/alacritty ~/.config/alacritty
ln -sf ~/dotfiles/fontconfig ~/.config/fontconfig
ln -sf ~/dotfiles/i3 ~/.config/i3
ln -sf ~/dotfiles/i3blocks ~/.config/i3blocks
ln -sf ~/dotfiles/nvim ~/.config/nvim
ln -sf ~/dotfiles/ranger ~/.config/ranger
