#!/usr/bin/env sh


ln -s ./bash_profile ../.bash_profile
ln -s ./bashrc ../.bashrc
ln -s ./xinitrc ../.xinitrc

ln -s ./alacritty/ ../.config/alacritty/
ln -s ./fontconfig/ ../.config/fontconfig/
ln -s ./i3/ ../.config/i3/
ln -s ./i3blocks/ ../.config/i3blocks/
ln -s ./nvim/ ../.config/nvim
ln -s ./ranger/ ../.config/ranger/
